### ISSUE TITLE
Developer track layout

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#29]
Below are the labs and the assignee 

- [x] API Design Lab @VinayBhalerao  https://github.com/RedHatWorkshops/dayinthelife-integration/issues/10
- [x] API Mock Lab @kasriniv   https://github.com/RedHatWorkshops/dayinthelife-integration/issues/12
- [x] Fuse Online and Eclipse che instructions @weimeilin79  @sigreen @VinayBhalerao https://github.com/RedHatWorkshops/dayinthelife-integration/issues/16 
- [x] API Management Lab [TBD] https://github.com/RedHatWorkshops/dayinthelife-integration/issues/13
- [x] UI @btierney  https://github.com/RedHatWorkshops/dayinthelife-integration/issues/27 and https://github.com/RedHatWorkshops/dayinthelife-integration/issues/28

**Comment by VinayBhalerao** [comment]
All labs are present. This was an old issue to keep track of all labs. Closing since it is no more used for tracking purpose.
